/** Declaration file generated by dts-gen */

declare module 'google-play-scraper' {

	export const age: {
		FIVE_UNDER: string
		NINE_UP: string
		SIX_EIGHT: string
	}

	export const category: {
		ANDROID_WEAR: string
		ART_AND_DESIGN: string
		AUTO_AND_VEHICLES: string
		BEAUTY: string
		BOOKS_AND_REFERENCE: string
		BUSINESS: string
		COMICS: string
		COMMUNICATION: string
		DATING: string
		EDUCATION: string
		ENTERTAINMENT: string
		EVENTS: string
		FAMILY: string
		FAMILY_ACTION: string
		FAMILY_BRAINGAMES: string
		FAMILY_CREATE: string
		FAMILY_EDUCATION: string
		FAMILY_MUSICVIDEO: string
		FAMILY_PRETEND: string
		FINANCE: string
		FOOD_AND_DRINK: string
		GAME: string
		GAME_ACTION: string
		GAME_ADVENTURE: string
		GAME_ARCADE: string
		GAME_BOARD: string
		GAME_CARD: string
		GAME_CASINO: string
		GAME_CASUAL: string
		GAME_EDUCATIONAL: string
		GAME_MUSIC: string
		GAME_PUZZLE: string
		GAME_RACING: string
		GAME_ROLE_PLAYING: string
		GAME_SIMULATION: string
		GAME_SPORTS: string
		GAME_STRATEGY: string
		GAME_TRIVIA: string
		GAME_WORD: string
		HEALTH_AND_FITNESS: string
		HOUSE_AND_HOME: string
		LIBRARIES_AND_DEMO: string
		LIFESTYLE: string
		MAPS_AND_NAVIGATION: string
		MEDICAL: string
		MUSIC_AND_AUDIO: string
		NEWS_AND_MAGAZINES: string
		PARENTING: string
		PERSONALIZATION: string
		PHOTOGRAPHY: string
		PRODUCTIVITY: string
		SHOPPING: string
		SOCIAL: string
		SPORTS: string
		TOOLS: string
		TRAVEL_AND_LOCAL: string
		VIDEO_PLAYERS: string
		WEATHER: string
	}

	export const collection: {
		GROSSING: string
		NEW_FREE: string
		NEW_PAID: string
		TOP_FREE: string
		TOP_PAID: string
		TRENDING: string
	}

	export const sort: {
		HELPFULNESS: number
		NEWEST: number
		RATING: number
	}

	export function app(opts: any): any

	export function developer(a0: any, ...args: any[]): any

	export function list(a0: any, ...args: any[]): any

	export function memoized(opts: any): any

	export function permissions(opts: any): any

	export function reviews(opts: any): any

	export function search(opts: {
		term: string
		num?: number
		lang?: string
		country?: string
		fullDetail?: boolean
		throttle?: number
		price?: 'all' | 'free' | 'paid'
	}): Promise<SearchResult[]>

	export function similar(a0: any, ...args: any[]): any

	export function suggest(opts: any): any

	export interface SearchResult {
		adSupported: boolean
		androidVersion: string
		androidVersionText: string
		appId: string
		comments: string[]
		contentRating: string
		description: string
		descriptionHTML: string
		developer: string
		developerAddress: string
		developerEmail: string
		developerId: string
		developerWebsite: string
		familyGenre: any
		familyGenreId: any
		free: boolean
		genre: string
		genreId: string
		histogram: { [key: string]: number }
		icon: string
		maxInstalls: number
		minInstalls: number
		offersIAP: boolean
		preregister: boolean
		price: string
		recentChanges: string[]
		reviews: number
		score: number
		screenshots: string[]
		size: string
		summary: string
		title: string
		updated: string
		url: string
		version: string
		video: string
	}

}


